/*
 * Copyright (c) 2018 Comvai, s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package biz.turnonline.ecosystem.account.client.model;

import java.io.Serializable;
import java.util.Date;

public class NewsletterSubscription
        implements Serializable
{
    private static final long serialVersionUID = -4671341588215251553L;

    private Boolean subscribe = false;

    private String code = null;

    private Date modification = null;

    /**
     * The boolean indication whether the contact will be subscribed or unsubscribed from the newsletter.
     **/
    public NewsletterSubscription subscribe( Boolean subscribe )
    {
        this.subscribe = subscribe;
        return this;
    }

    public Boolean getSubscribe()
    {
        return subscribe;
    }

    public void setSubscribe( Boolean subscribe )
    {
        this.subscribe = subscribe;
    }

    /**
     * The security code originally generated by the service.
     **/
    public NewsletterSubscription code( String code )
    {
        this.code = code;
        return this;
    }

    public String getCode()
    {
        return code;
    }

    public void setCode( String code )
    {
        this.code = code;
    }

    /**
     * The newsletter subscription modification date and time. A client specified time when the request has been originated.
     **/
    public NewsletterSubscription modification( Date modification )
    {
        this.modification = modification;
        return this;
    }

    public Date getModification()
    {
        return modification;
    }

    public void setModification( Date modification )
    {
        this.modification = modification;
    }

    @Override
    public String toString()
    {
        return "class NewsletterSubscription {\n" +
                "    subscribe: " + toIndentedString( subscribe ) + "\n" +
                "    code: " + toIndentedString( code ) + "\n" +
                "    modification: " + toIndentedString( modification ) + "\n" +
                "}";
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString( Object o )
    {
        if ( o == null )
        {
            return "null";
        }
        return o.toString().replace( "\n", "\n    " );
    }
}
