/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 1969-12-31 23:59:59 UTC)
 * on 2022-05-04 at 21:49:23 UTC
 * Modify at your own risk.
 */

package biz.turnonline.ecosystem.steward.model;

import java.io.Serializable;

/**
 * Model definition for OpeningHoursRegular.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the TurnOnline.biz Account Steward. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
public final class OpeningHoursRegular
        implements Serializable
{
    private static final long serialVersionUID = 7260273439342614814L;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String friday;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String monday;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String saturday;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String sunday;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String thursday;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String tuesday;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String wednesday;

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getFriday()
    {
        return friday;
    }

    /**
     * @param friday friday or {@code null} for none
     */
    public OpeningHoursRegular setFriday( java.lang.String friday )
    {
        this.friday = friday;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getMonday()
    {
        return monday;
    }

    /**
     * @param monday monday or {@code null} for none
     */
    public OpeningHoursRegular setMonday( java.lang.String monday )
    {
        this.monday = monday;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getSaturday()
    {
        return saturday;
    }

    /**
     * @param saturday saturday or {@code null} for none
     */
    public OpeningHoursRegular setSaturday( java.lang.String saturday )
    {
        this.saturday = saturday;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getSunday()
    {
        return sunday;
    }

    /**
     * @param sunday sunday or {@code null} for none
     */
    public OpeningHoursRegular setSunday( java.lang.String sunday )
    {
        this.sunday = sunday;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getThursday()
    {
        return thursday;
    }

    /**
     * @param thursday thursday or {@code null} for none
     */
    public OpeningHoursRegular setThursday( java.lang.String thursday )
    {
        this.thursday = thursday;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getTuesday()
    {
        return tuesday;
    }

    /**
     * @param tuesday tuesday or {@code null} for none
     */
    public OpeningHoursRegular setTuesday( java.lang.String tuesday )
    {
        this.tuesday = tuesday;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getWednesday()
    {
        return wednesday;
    }

    /**
     * @param wednesday wednesday or {@code null} for none
     */
    public OpeningHoursRegular setWednesday( java.lang.String wednesday )
    {
        this.wednesday = wednesday;
        return this;
    }
}
