/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 1969-12-31 23:59:59 UTC)
 * on 2022-05-04 at 21:49:23 UTC
 * Modify at your own risk.
 */

package biz.turnonline.ecosystem.steward.model;

import java.io.Serializable;

/**
 * Model definition for PickupPointDirections.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the TurnOnline.biz Account Steward. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
public final class PickupPointDirections
        implements Serializable
{
    private static final long serialVersionUID = -4351707426218630276L;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String car;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String publicTransport;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String walk;

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getCar()
    {
        return car;
    }

    /**
     * @param car car or {@code null} for none
     */
    public PickupPointDirections setCar( java.lang.String car )
    {
        this.car = car;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getPublicTransport()
    {
        return publicTransport;
    }

    /**
     * @param publicTransport publicTransport or {@code null} for none
     */
    public PickupPointDirections setPublicTransport( java.lang.String publicTransport )
    {
        this.publicTransport = publicTransport;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getWalk()
    {
        return walk;
    }

    /**
     * @param walk walk or {@code null} for none
     */
    public PickupPointDirections setWalk( java.lang.String walk )
    {
        this.walk = walk;
        return this;
    }
}
