/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 1969-12-31 23:59:59 UTC)
 * on 2022-05-04 at 21:49:23 UTC
 * Modify at your own risk.
 */

package biz.turnonline.ecosystem.steward.model;

import java.io.Serializable;

/**
 * Model definition for PickupPoint.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the TurnOnline.biz Account Steward. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
public final class PickupPoint
        implements Serializable
{
    private static final long serialVersionUID = 3870233341888337379L;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private PickupPointAddress address;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private PickupPointCoordinates coordinates;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private PickupPointDirections directions;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.Double distanceFromOrigin;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String externalId;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String name;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private PickupPointOpeningHours openingHours;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private PickupPointPhotos photos;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String url;

    /**
     * @return value or {@code null} for none
     */
    public PickupPointAddress getAddress()
    {
        return address;
    }

    /**
     * @param address address or {@code null} for none
     */
    public PickupPoint setAddress( PickupPointAddress address )
    {
        this.address = address;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public PickupPointCoordinates getCoordinates()
    {
        return coordinates;
    }

    /**
     * @param coordinates coordinates or {@code null} for none
     */
    public PickupPoint setCoordinates( PickupPointCoordinates coordinates )
    {
        this.coordinates = coordinates;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public PickupPointDirections getDirections()
    {
        return directions;
    }

    /**
     * @param directions directions or {@code null} for none
     */
    public PickupPoint setDirections( PickupPointDirections directions )
    {
        this.directions = directions;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.Double getDistanceFromOrigin()
    {
        return distanceFromOrigin;
    }

    /**
     * @param distanceFromOrigin distanceFromOrigin or {@code null} for none
     */
    public PickupPoint setDistanceFromOrigin( java.lang.Double distanceFromOrigin )
    {
        this.distanceFromOrigin = distanceFromOrigin;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getExternalId()
    {
        return externalId;
    }

    /**
     * @param externalId externalId or {@code null} for none
     */
    public PickupPoint setExternalId( java.lang.String externalId )
    {
        this.externalId = externalId;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getName()
    {
        return name;
    }

    /**
     * @param name name or {@code null} for none
     */
    public PickupPoint setName( java.lang.String name )
    {
        this.name = name;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public PickupPointOpeningHours getOpeningHours()
    {
        return openingHours;
    }

    /**
     * @param openingHours openingHours or {@code null} for none
     */
    public PickupPoint setOpeningHours( PickupPointOpeningHours openingHours )
    {
        this.openingHours = openingHours;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public PickupPointPhotos getPhotos()
    {
        return photos;
    }

    /**
     * @param photos photos or {@code null} for none
     */
    public PickupPoint setPhotos( PickupPointPhotos photos )
    {
        this.photos = photos;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getUrl()
    {
        return url;
    }

    /**
     * @param url url or {@code null} for none
     */
    public PickupPoint setUrl( java.lang.String url )
    {
        this.url = url;
        return this;
    }
}
